#!/usr/bin/env python3
"""Generate the CLI reference from the command's own help.

TEMPLATE: copy into the product repo's scripts/ and adapt the ADAPT points.

Two common shapes are shown below; keep the one that matches the project and
delete the other. Either way the output is generated-from-source and
drift-checked: change the CLI and CI ("Docs Reference Freshness") regenerates and
fails on drift. Wire it into `make docs-reference`.

Usage: python scripts/gen_cli_reference.py
"""

from __future__ import annotations

import inspect
import pathlib

# ADAPT: output path and the tool name used throughout the header.
OUT = pathlib.Path("docs-mintlify/reference/cli.mdx")

HEADER = """\
---
title: CLI reference
description: The <your-tool> command-line interface.
icon: terminal
---

{/* GENERATED by scripts/gen_cli_reference.py — do not edit by hand. */}

The `<your-tool>` console script. See [Install](/install) for setup and
[Configuration](/reference/configuration) for settings.
"""


# --- Shape 1: a hand-parsed CLI whose module docstring IS the help text -------
def from_docstring() -> str:
    # ADAPT: import the entry-point function whose __doc__ is the help text.
    from your_package.server import main

    help_text = inspect.cleandoc(main.__doc__ or "")
    return HEADER + "\n```text\n<your-tool> [subcommand]\n\n" + help_text + "\n```\n"


# --- Shape 2: a Click/Typer app (introspect commands + params) ----------------
def from_click() -> str:
    # ADAPT: import the Click group / Typer app object.
    import click
    from your_package.cli import cli  # a click.Group

    out = [HEADER]
    ctx = click.Context(cli, info_name="<your-tool>")
    for name in sorted(cli.commands):
        cmd = cli.commands[name]
        command_ctx = click.Context(cmd, info_name=name, parent=ctx)
        out.append(f"\n## `{name}`\n")
        if cmd.help:
            out.append(" ".join(cmd.help.split()) + "\n")
        # Include a synopsis line for fast scanning.
        usage = cmd.get_usage(command_ctx).replace("Usage: ", "")
        out.append(f"```text\n{usage}\n```\n")
        # Params as <ParamField> blocks (see references/reference-patterns.md).
        options = [p for p in cmd.get_params(command_ctx) if isinstance(p, click.Option)]
        options.sort(key=lambda option: max(option.opts, key=len))
        for p in options:
            flag = max(p.opts, key=len)
            req = " required" if p.required else ""
            typ = getattr(p.type, "name", None) or str(p.type)
            out.append(f'<ParamField path="{flag}" type="{typ}"{req}>')
            out.append(f"{(p.help or '').strip()}")
            out.append("</ParamField>\n")
    return "\n".join(out)


def main_() -> None:
    # ADAPT: call the shape that matches the project.
    body = from_docstring()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main_()
