#!/usr/bin/env python3
"""Generate the MCP tool reference from the live FastMCP instance.

TEMPLATE: copy into the product repo's scripts/ and adapt the ADAPT points.

Introspects every registered tool (name, description, parameters, annotations),
grouped by read-only / writes / destructive, so a new or changed tool shows up
automatically and the reference cannot drift from the code. Wire it into
`make docs-reference`; CI ("Docs Reference Freshness") regenerates and fails if
the committed output differs.

Usage: python scripts/gen_mcp_reference.py   (needs the package installed)
"""

from __future__ import annotations

import asyncio
import pathlib

# ADAPT: import path of the module that registers tools on the FastMCP instance.
# Importing it must register every tool on the shared `mcp` instance.
from your_package.server import mcp

# ADAPT: output path and tool name in the header text.
OUT = pathlib.Path("docs-mintlify/reference/mcp-tools.mdx")

HEADER = """\
---
title: MCP tool reference
description: Every tool the <your-tool> server exposes, by kind.
icon: wrench
---

{/* GENERATED by scripts/gen_mcp_reference.py — do not edit by hand. */}

These are the tools an MCP client can call. Each is marked **read-only**,
**writes** (creates account state), or **destructive** (not trivially
reversible) from its MCP annotations, so clients can decide when to confirm.
See [Install](/install) for setup.
"""

ORDER = ["read-only", "writes", "destructive"]
LABELS = {"read-only": "Read-only", "writes": "Writes", "destructive": "Destructive"}


def _kind(tool) -> str:
    a = tool.annotations
    if a and getattr(a, "readOnlyHint", None):
        return "read-only"
    if a and getattr(a, "destructiveHint", None):
        return "destructive"
    return "writes"


def _first_para(text: str | None) -> str:
    if not text:
        return ""
    first = text.strip().split("\n\n", 1)[0]
    # Collapse internal whitespace so output is deterministic across machines.
    return " ".join(first.split())


def _type_str(spec: dict) -> str:
    if "type" in spec:
        t = spec["type"]
        if t == "array":
            items = spec.get("items", {})
            inner = items.get("type") or "object"
            return f"{inner}[]"
        if isinstance(t, list):
            return " \\| ".join(str(item) for item in t if item != "null") or "any"
        return str(t)
    for key in ("anyOf", "oneOf"):
        if key in spec:
            ts = [s.get("type") for s in spec[key] if s.get("type") not in (None, "null")]
            if ts:
                return " \\| ".join(ts)
    return "any"


def _param_rows(schema: dict) -> list[tuple[str, str, str, str]]:
    props = (schema or {}).get("properties", {})
    required = set((schema or {}).get("required", []))
    rows = []
    for name in sorted(props):
        spec = props[name]
        desc = " ".join((spec.get("description") or "").split())
        desc = desc.replace("|", "\\|")
        rows.append((name, _type_str(spec), "yes" if name in required else "no", desc))
    return rows


def main() -> None:
    tools = asyncio.run(mcp.list_tools())
    by_kind: dict[str, list] = {k: [] for k in ORDER}
    for t in tools:
        by_kind[_kind(t)].append(t)

    out = [HEADER]
    for kind in ORDER:
        group = sorted(by_kind[kind], key=lambda x: x.name)
        if not group:
            continue
        out.append(f"\n## {LABELS[kind]}\n")
        for t in group:
            out.append(f"### `{t.name}`\n")
            out.append(f"**{LABELS[kind]}.** {_first_para(t.description)}\n")
            rows = _param_rows(t.inputSchema)
            if rows:
                out.append("| Parameter | Type | Required | Description |")
                out.append("| --- | --- | --- | --- |")
                for name, typ, req, desc in rows:
                    out.append(f"| `{name}` | {typ} | {req} | {desc} |")
                out.append("")
            else:
                out.append("_No parameters._\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(tools)} tools)")


if __name__ == "__main__":
    main()
